In [1]:
import numpy as np

# Ways to build array in numpy

In [2]:
arr_1 = np.array([2,3,65,7,9,7,5,4,2,3])

In [3]:
print(arr_1)

[ 2  3 65  7  9  7  5  4  2  3]


In [4]:
arr_2 = np.arange(8)

In [5]:
arr_2

array([0, 1, 2, 3, 4, 5, 6, 7])

In [6]:
# arr_3 = np.arange(10,21)
arr_3 = np.arange(10,41,2)

In [7]:
arr_3

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40])

In [8]:
arr_4 = np.zeros([4,4])

In [9]:
arr_4

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [10]:
arr_5 = np.ones([4,4])

In [11]:
arr_5

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [17]:
np.zeros([2,6], order='F')

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [18]:
np.identity(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [23]:
arr_6 = np.linspace(1,5,10,retstep=True)

In [24]:
arr_6

(array([ 1.        ,  1.44444444,  1.88888889,  2.33333333,  2.77777778,
         3.22222222,  3.66666667,  4.11111111,  4.55555556,  5.        ]),
 0.44444444444444442)

In [25]:
nd_1 = np.array([[1,2,3,4,5,6],[7,6,5,4,3,2],[9,8,1,2,3,5],[11,13,15,16,18,19]])

In [26]:
nd_1

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  6,  5,  4,  3,  2],
       [ 9,  8,  1,  2,  3,  5],
       [11, 13, 15, 16, 18, 19]])

In [27]:
nd_1.shape

(4, 6)

In [29]:
nd_1 = nd_1.reshape(6,4)

In [30]:
nd_1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  6],
       [ 5,  4,  3,  2],
       [ 9,  8,  1,  2],
       [ 3,  5, 11, 13],
       [15, 16, 18, 19]])

In [31]:
nd_1.ndim

2

In [32]:
nd_1.reshape(-1,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  6,  5,  4,  3,  2],
       [ 9,  8,  1,  2,  3,  5],
       [11, 13, 15, 16, 18, 19]])

In [37]:
nd_1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  6],
       [ 5,  4,  3,  2],
       [ 9,  8,  1,  2],
       [ 3,  5, 11, 13],
       [15, 16, 18, 19]])

In [39]:
nd_1[0:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 6]])

In [40]:
nd_1[:,0:2]

array([[ 1,  2],
       [ 5,  6],
       [ 5,  4],
       [ 9,  8],
       [ 3,  5],
       [15, 16]])

In [41]:
nd_1[0:2,0:3]

array([[1, 2, 3],
       [5, 6, 7]])