In [1]:
import numpy as np

# Numpy Methods

In [2]:
arr_1 = np.array([[1,2,3,4,5,6],[7,6,5,4,3,2],[9,8,1,2,3,5],[11,13,15,16,18,19]])

In [4]:
arr_1

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  6,  5,  4,  3,  2],
       [ 9,  8,  1,  2,  3,  5],
       [11, 13, 15, 16, 18, 19]])

In [6]:
# flat the array - convert 2D to 1D
print(arr_1.flatten())

[ 1  2  3  4  5  6  7  6  5  4  3  2  9  8  1  2  3  5 11 13 15 16 18 19]


In [7]:
arr_1 = arr_1.flatten()

In [8]:
arr_1.sort()

In [9]:
arr_1

array([ 1,  1,  2,  2,  2,  3,  3,  3,  4,  4,  5,  5,  5,  6,  6,  7,  8,
        9, 11, 13, 15, 16, 18, 19])

In [10]:
arr_2 = np.array([2,3,4,5,6,8,12,11,15,19,21,9,23,5])

In [11]:
arr_2.argsort()

array([ 0,  1,  2,  3, 13,  4,  5, 11,  7,  6,  8,  9, 10, 12], dtype=int64)

In [12]:
arr_2.argmax()

12

In [13]:
arr_2.max()

23

In [16]:
arr_2.partition(5)

In [17]:
arr_2

array([ 3,  2,  4,  5,  5,  6,  8, 11,  9, 12, 21, 19, 23, 15])

In [18]:
arr_3 = np.array([2,3,4,5,6,8,12,11,15,19,21,9,23,5])

In [19]:
np.unique(arr_3)

array([ 2,  3,  4,  5,  6,  8,  9, 11, 12, 15, 19, 21, 23])

In [20]:
np.unique(arr_3, return_counts=True)

(array([ 2,  3,  4,  5,  6,  8,  9, 11, 12, 15, 19, 21, 23]),
 array([1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64))

In [21]:
np.mean(arr_3)

10.214285714285714

In [22]:
np.median(arr_3)

8.5

In [23]:
x = np.array([1,2,3,4,5,6,7,8,9])

In [24]:
len(x)

9

In [25]:
np.median(x)

5.0

In [26]:
x = np.array([1,2,3,4,5,6,7,8,9,10])

In [27]:
np.median(x)

5.5