In [1]:
import numpy as np

In [2]:
x = np.array([2,3,4,5,7,8,8,0,2,3,5,7])

In [3]:
print(x)

[2 3 4 5 7 8 8 0 2 3 5 7]


In [4]:
data = [2,3,4,6,8,9,'hi','hello']

In [5]:
list_1 = list(data)
arr_1 = np.array(data)

In [6]:
list_1

[2, 3, 4, 6, 8, 9, 'hi', 'hello']

In [7]:
arr_1

array(['2', '3', '4', '6', '8', '9', 'hi', 'hello'],
      dtype='<U11')

In [8]:
data = [2,3,4,6,8,9,'hi','hello',10.5,True]

In [9]:
arr_1 = np.array(data)

In [10]:
arr_1

array(['2', '3', '4', '6', '8', '9', 'hi', 'hello', '10.5', 'True'],
      dtype='<U11')

In [11]:
data = [2,3,4,6,8,9,10.5,True]

In [12]:
arr_1 = np.array(data)

In [13]:
arr_1

array([  2. ,   3. ,   4. ,   6. ,   8. ,   9. ,  10.5,   1. ])

In [14]:
# Memory Issue with list
import sys

In [15]:
sys.getsizeof(list())

64

In [17]:
sys.getsizeof(np.array([]))

96

In [18]:
x = [1,2,4,5,6]
sys.getsizeof(x)

104

In [20]:
x = 0
# sys.getsizeof(int())
sys.getsizeof(x)

24

In [21]:
x = 1
sys.getsizeof(x)

28

In [23]:
x = [1,2,4,5,6]
sys.getsizeof(np.array(x))

116

In [25]:
x = [i for i in range(1,100000)]

In [26]:
sys.getsizeof(x)

824464

In [27]:
sys.getsizeof(np.array(x))

400092

In [28]:
arr_1 = np.array([2,3,4,6,8])
arr_2 = np.array([5,8,9,2,1])

In [29]:
arr_1 + arr_2

array([ 7, 11, 13,  8,  9])

In [30]:
list_1 = [2,3,5,6,8]
list_2 = [7,8,9,2,1]

In [31]:
list_1 + list_2

[2, 3, 5, 6, 8, 7, 8, 9, 2, 1]